### ISSUE TITLE
$eval not working as expected

### ISSUE THREAD

**Issue by yesoreyeram** [xiatechs/jsonata-go#24]
It appears that the `$eval` doesn't work as expected.

Input

```json
{
  "inputs" : [
	  {
		  "a" : 1,
		  "b" : "{\"c\":11}"
	  },
	  {
		  "a" : 2,
		  "b": "{\"c\":22}"
	  }
  ]
}
```

and the corresponding jsonata

```js
$map(inputs,function($v){{
  "a": $v.a,
  "b": $v.b,
  "c": $eval($v.b).c
}})
```

should produce something like [this](https://try.jsonata.org/0ZG3_xD4w)

```json
[
  {
    "a": 1,
    "b": "{\"c\":11}",
    "c": 11
  },
  {
    "a": 2,
    "b": "{\"c\":22}",
    "c": 22
  }
]
```

instead I am getting,

```json
[
  {
    "a": 1,
    "b": "{\"c\":11}"
  },
  {
    "a": 2,
    "b": "{\"c\":22}"
  }
]
```

as you can see, "c" is silently failing

**Comment by tbal999** [comment]
hey @yesoreyeram good observation - the $eval placed in this fork of go-jsonata is different from js jsonata

the method is

```
func RunEval(initialContext reflect.Value, expression ...interface{}) (interface{}, error) {
```

for it to work you need to pass in initial context. In this case, initial context is irrelevant so you can just pass ""

i.e

```
$map(inputs,function($v){{
  "a": $v.a,
  "b": $v.b,
  "c": $eval("", $v.b).c
}})
```
