### ISSUE TITLE
Getting a list of variables

### ISSUE THREAD

**Issue by xgamtx** [xiatechs/jsonata-go#27]
Hello! Is it possible to get a list of variables to evaluate formula? e.g.:
Formula: 
```
$average([accuracy1, accuracy2])
```
I'd like to get a list:
```
[]string{"accuracy1", "accuracy2"}
```

**Comment by tbal999** [comment]
if your question is "how do i create a list in go-jsonata" (which i'm not sure it is, if not - please provide more context):

in go-jsonata, array syntax is as simple as open square bracket, items delimited by command, close square bracket.

i.e

{
 "array": [1,2,3,4,5]
}

**Comment by xgamtx** [comment]
Thank you for **soo** fast answer!
I have a list of variables, I can calculate. But I'm getting formula from an external source. I'd like to check if the formula needs only variables I can calculate or not.
```
availableVariables := []string{"accuracy1", "base"}     // list of variables I can calculate
gotFormula := "$average([accuracy1, accuracy2]) + base" // a formula from an external source
expr, err  := jsonata.Compile(formula)
if err != nil {
	log.Fatal("Invalid expression", err)
	return
}
requiredVariables := expr.GetVariables()  // []string{"accuracy1", "accuracy2", "base"}
// check if requiredVariables and availableVariables are equal or not
```
I'd like to have method like `GetVariables`
