### ISSUE TITLE
add $eval function

### ISSUE THREAD

**Issue by andyh565** [xiatechs/jsonata-go#8]
Hello, is it possible to add the $eval function as defined:

https://docs.jsonata.org/string-functions#eval

Thanks.

**Comment by tbal999** [comment]
sure - will add it soon

**Comment by tbal999** [comment]
have added code that adheres to behaviour described in your link

i.e

```$eval('[1,$string(2),3]')```

==

[
    1,
    "2",
    3
]

**Comment by tbal999** [comment]
re-open again if you find it does not match expectation

**Comment by andyh565** [comment]
that's awesome. Thanks you!
